YeoDamHuman/Travel_Back

- Back-end/build.gradle
- Back-end/src/test/java/com/example/backend/BackEndApplicationTests.java
- Back-end/src/test/java/resources/application.properties
테스트 코드에 test 프로파일을 활성화시켜서 임시방편으로 해놓음
> CI Error Solve

- Back-end/build.gradle
- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/group/entity/Group.java
- Back-end/src/main/java/com/example/backend/jwt/config/JWTGenerator.java
- Back-end/src/main/java/com/example/backend/jwt/dto/JwtDto.java
- Back-end/src/main/java/com/example/backend/jwt/filter/JwtAuthenticationFilter.java
- Back-end/src/main/java/com/example/backend/jwt/provider/JwtProvider.java
- Back-end/src/main/java/com/example/backend/user/controller/UserController.java
- Back-end/src/main/java/com/example/backend/user/dto/UserRequest.java
- Back-end/src/main/java/com/example/backend/user/entity/User.java
- Back-end/src/main/java/com/example/backend/user/repository/UserRepository.java
- Back-end/src/main/java/com/example/backend/user/service/UserService.java
로그인이랑 회원가입 그리고 JWT 완료
User 테이블에 user_role 컬럼 추가
> Login, Register, JWT, UserEntity 🚀

- .idea/.gitignore
- .idea/Back.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- Back-end/build.gradle
- Back-end/src/main/java/com/example/backend/common/config/RedisConfig.java
- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/mail/controller/MailController.java
- Back-end/src/main/java/com/example/backend/mail/dto/request/MailRequest.java
- Back-end/src/main/java/com/example/backend/mail/dto/response/MailResponse.java
- Back-end/src/main/java/com/example/backend/mail/service/MailService.java
Email 기능 구현 및 폴더 구조 변경 .idea 삭제
(노션에 올려놓은 내용 무조건 필독 바람!)
> Email Verification, Folder Structure, .idea 

- Back-end/src/main/resources/resources.txt
✅ 의존성, 환경 변수, 빌드 관련 코드 업데이트
main
resources 폴더 삭제가 되서 더미 파일 넣어서 폴더 유지
> docs: resources폴더에 설명 txt 생성 📝

- Back-end/src/main/java/com/example/backend/user/controller/UserController.java
- Back-end/src/main/java/com/example/backend/user/service/UserService.java
- #23 
UUID userID = getCurrentUserId(); 이렇게 해서 받아오는 코드 삭제하고 바로 받을 수 있게 수정 정보 조회 Controller에서 UserId 받는거에서 안받는걸로 리팩터링
어떤 변경 사항이 있나요?
> ♻️ REFACTOR : 쓸데없는 코드 삭제 및 코드 리팩터링

- Back-end/src/main/java/com/example/backend/common/auth/AuthUtil.java
- Back-end/src/main/java/com/example/backend/group/controller/GroupController.java
- Back-end/src/main/java/com/example/backend/group/dto/request/GroupRequest.java
- Back-end/src/main/java/com/example/backend/group/dto/response/GroupResponse.java
- Back-end/src/main/java/com/example/backend/group/entity/Group.java
- Back-end/src/main/java/com/example/backend/group/service/GroupService.java
- Back-end/src/main/java/com/example/backend/user/filter/UserFilter.java
- Back-end/src/main/java/com/example/backend/user/service/UserService.java
- #31 
- #23 
현재 유저 알아오는 로직이 공통으로 많이 쓰여서 auth 쪽으로 분리했음 
어떤 변경 사항이 있나요?
> ✨, ♻️ FEAT, REFACTOR :  그룹 생성 기능 구현 및 로그인 로직 필터랑 현재 유저 알아오는거 각각 클래스로 분리

- Back-end/src/main/java/com/example/backend/group/controller/GroupController.java
- Back-end/src/main/java/com/example/backend/group/dto/response/GroupResponse.java
- Back-end/src/main/java/com/example/backend/group/repository/GroupRepository.java
- Back-end/src/main/java/com/example/backend/group/service/GroupService.java
- #31 
그룹 생성, 그룹 목록 조회, 그룹 인원 추가, 그룹 인원 삭제, 그룹 삭제, 그룹 인원 카운팅 기능 개발했습니다.
어떤 변경 사항이 있나요?
> ✨ FEAT : 그룹 기능 개발

- Back-end/src/main/java/com/example/backend/user/service/UserService.java
- #23 
회원가입시 이미지를 안주면 기본 이미지로 준다.
어떤 변경 사항이 있나요?
> ♻️ REFACTOR : 유저 회원가입 로직 변경

- Back-end/src/main/java/com/example/backend/common/config/SwaggerConfig.java
- Back-end/src/main/java/com/example/backend/user/service/UserService.java
회원가입 시 중복검사 로직이 또 발견되서 수정했다
어떤 변경 사항이 있나요?
> 🐛 FIX : 회원가입 내 중복검사 오류 수정

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/weather/controller/WeatherController.java
- Back-end/src/main/java/com/example/backend/weather/dto/response/WeatherResponse.java
- Back-end/src/main/java/com/example/backend/weather/service/WeatherService.java
- #40 
OpenWeatherMap API를 연동하여 도시별 현재 날씨 정보를 조회하는 기능을 추가했고 사용자가 도시 이름(영문)을 입력하면 실시간 기온, 습도, 날씨 상태 등을 응답한다.
어떤 변경 사항이 있나요?
> ✨ FEAT: 날씨 API 연동 및 조회 기능 구현

- Back-end/src/main/java/com/example/backend/board/dto/request/BoardRequestDto.java
- Back-end/src/main/java/com/example/backend/board/dto/request/BoardUpdateRequestDto.java
- Back-end/src/main/java/com/example/backend/board/dto/response/BoardDetailResponseDto.java
- Back-end/src/main/java/com/example/backend/board/entity/Board.java
- Back-end/src/main/java/com/example/backend/board/entity/BoardImage.java
- Back-end/src/main/java/com/example/backend/board/repository/BoardRepository.java
- Back-end/src/main/java/com/example/backend/board/service/BoardService.java
#47 
어떤 변경 사항이 있나요?
게시판에 이미지가 하나밖에 들어가지 않는 오류 수정
- [] 새로운 기능 추가
> 🐛 FIX : 게시판 이미지 단일에서 리스트로 여러개 가능하도록 수정

- Back-end/src/main/java/com/example/backend/scheduleItem/entity/ScheduleItem.java
> [REFACTOR] 스케쥴 아이템 order 백틱으로 감싸기

- Back-end/src/main/java/com/example/backend/cart/service/CartService.java
- Back-end/src/main/java/com/example/backend/schedule/controller/ScheduleController.java
- Back-end/src/main/java/com/example/backend/schedule/dto/request/ScheduleRequest.java
- Back-end/src/main/java/com/example/backend/schedule/filter/ScheduleFilter.java
- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
스케쥴이 말 안들어서 혼쭐좀 내줬습니다;;
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
> ♻️ REFACTOR : 스케쥴 수정

- .gitignore
- Back-end/src/main/java/com/example/backend/cart/controller/CartController.java
- Back-end/src/main/java/com/example/backend/cart/service/CartService.java
- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/region/controller/RegionController.java
- Back-end/src/main/java/com/example/backend/region/repository/RegionRepository.java
- Back-end/src/main/java/com/example/backend/region/service/RegionService.java
- Back-end/src/main/java/com/example/backend/tour/webclient/TourApiClient.java
contentTypeId를 기준으로 테마를 조회하도록 변경.
어떤 변경 사항이 있나요?
> REFACTOR: contentTypeId 기준으로 조회하도록 변경

- Back-end/src/main/java/com/example/backend/weather/controller/WeatherController.java
- Back-end/src/main/java/com/example/backend/weather/converter/City.java
- Back-end/src/main/java/com/example/backend/weather/service/WeatherService.java
> ♻️ REFACTOR : 날씨 수정

- Back-end/src/main/java/com/example/backend/board/dto/response/BoardListResponseDto.java
- Back-end/src/main/java/com/example/backend/board/service/BoardService.java
> fix: 게시판 리스트 조회 시 이미지 배열처리

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/common/config/SwaggerConfig.java
> fix: 도메인 연결 오류 수정

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
> devOps: https통신 설정

- Back-end/src/main/java/com/example/backend/schedule/dto/request/ScheduleRequest.java
- Back-end/src/main/java/com/example/backend/schedule/dto/response/ScheduleResponse.java
- Back-end/src/main/java/com/example/backend/schedule/entity/Schedule.java
- Back-end/src/main/java/com/example/backend/schedule/service/AiService.java
- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
- Back-end/src/main/java/com/example/backend/scheduleItem/dto/request/ScheduleItemRequest.java
- Back-end/src/main/java/com/example/backend/scheduleItem/entity/ScheduleItem.java
> ♻️ REFACTOR : Schedule 엔티티및 서비스 수정

- Back-end/src/main/java/com/example/backend/schedule/dto/response/ScheduleResponse.java
- Back-end/src/main/java/com/example/backend/schedule/service/AiService.java
- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
- Back-end/src/main/java/com/example/backend/tour/webclient/TourApiClient.java
> REFACTOR : AI 수정

- Back-end/src/main/java/com/example/backend/tour/entity/Tour.java
> FIX: content_id에 unique 키 추가

- Back-end/src/main/java/com/example/backend/cart/controller/CartController.java
- Back-end/src/main/java/com/example/backend/cart/dto/response/CartResponse.java
- Back-end/src/main/java/com/example/backend/cart/service/CartService.java
- Back-end/src/main/java/com/example/backend/favorite/controller/FavoriteController.java
- Back-end/src/main/java/com/example/backend/favorite/dto/response/FavoriteResponse.java
- Back-end/src/main/java/com/example/backend/favorite/entity/Favorite.java
- Back-end/src/main/java/com/example/backend/favorite/repository/FavoriteRepository.java
- Back-end/src/main/java/com/example/backend/favorite/service/FavoriteService.java
- Back-end/src/main/java/com/example/backend/tour/repository/TourRepository.java
- Back-end/src/main/java/com/example/backend/tour/webclient/TourApiClient.java
> FEAT: 카트 중복 수정 및 특정 지역에 대한 즐겨찾기 목록 조회 api 구현

- Back-end/src/main/java/com/example/backend/board/dto/response/BoardDetailResponseDto.java
- Back-end/src/main/java/com/example/backend/board/dto/response/BoardListResponseDto.java
- Back-end/src/main/java/com/example/backend/board/service/BoardService.java
- Back-end/src/main/java/com/example/backend/schedule/entity/Schedule.java
어떤 변경 사항이 있나요?
스케쥴 ID 반환 및 게시판 작성 시 더이상 작성 X
> Feat: 게시판 작성 시 스케쥴 사용 처리

- Back-end/src/main/java/com/example/backend/schedule/dto/request/ScheduleRequest.java
> REFACTOR : 스케쥴 수정 API 수정

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
> DevOps: 프론트 배포 주소 CORS 허용

- Back-end/src/main/java/com/example/backend/scheduleItem/controller/ScheduleItemController.java
- Back-end/src/main/java/com/example/backend/scheduleItem/dto/request/ScheduleItemRequest.java
- Back-end/src/main/java/com/example/backend/scheduleItem/service/ScheduleItemService.java
> Fix: 스케쥴 수정 및 삭제 수정

- Back-end/build.gradle
> REFACTOR : build.gradle 수정

- Back-end/src/main/java/com/example/backend/board/entity/Board.java
- Back-end/src/main/java/com/example/backend/board/service/BoardService.java
> Feat: 게시판 상세조회시 조회수 증가 로직 구현

- Back-end/src/main/java/com/example/backend/schedule/dto/response/ScheduleResponse.java
- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
> Fix: 마이페이지 스케쥴 조회 시 이미지 반환

- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
> Fix: 이미지 반환 오류 수정

- Back-end/src/main/java/com/example/backend/schedule/dto/request/ScheduleRequest.java
- Back-end/src/main/java/com/example/backend/schedule/dto/response/ScheduleResponse.java
- Back-end/src/main/java/com/example/backend/schedule/entity/Schedule.java
- Back-end/src/main/java/com/example/backend/schedule/service/ScheduleService.java
> REFACTOR : 스케쥴 수정

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
> REFACTOR : CORS 설정

- Back-end/src/main/java/com/example/backend/user/kakao/controller/KakaoController.java
- Back-end/src/main/java/com/example/backend/user/kakao/dto/request/KakaoRequest.java
- Back-end/src/main/java/com/example/backend/user/kakao/service/KakaoService.java
> REFACTOR : KAKAO 서비스 로직 수정

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
- Back-end/src/main/java/com/example/backend/user/kakao/controller/KakaoController.java
- Back-end/src/main/resources/resources.txt
- Back-end/src/main/resources/static/.well-known/assetlinks.json
> REFACTOR : 서비스 리팩터

- Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
> fix: CORS오류 수정

- Back-end/src/main/java/com/example/backend/schedule/service/AiService.java
- Back-end/src/main/java/com/example/backend/user/kakao/controller/KakaoController.java
- Back-end/src/main/java/com/example/backend/user/kakao/service/KakaoService.java
> Fix: AI프롬프팅
